name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - example/**
      - tests/**
      - LICENSE.md
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - example/**
      - tests/**
      - LICENSE.md
      - README.md
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4.0.1
        name: Install .NET 8
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'ga'
      - name: Restore .NET tools
        run: dotnet tool restore
      - name: Build
        run: |
          dotnet cake build.cake --bootstrap
          dotnet cake build.cake --pack
      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4.3.4
        with:
          name: package
          path: .\artifacts\packages
      - uses: NuGet/setup-nuget@v2.0.0
        name: Push NuGet package
        with:
          nuget-api-key: ${{ secrets.NUGET_ACTIONS }}
          nuget-api-key-source: https://api.nuget.org/v3/index.json
      - run: nuget push .\artifacts\packages -SkipDuplicate -NonInteractive
        
